#!/usr/bin/env bash

target_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
repo_root="$(cd "${target_dir}/../.." && pwd)"
tools_dir="${target_dir}/tools"

export LITEFURY_USER_DEVICE="${LITEFURY_USER_DEVICE:-/dev/xdma0_user}"
export LITEFURY_GOLDEN_BASE="${LITEFURY_GOLDEN_BASE:-0x7000}"
export LITEFURY_APP_BASE="${LITEFURY_APP_BASE:-0x6000}"
export LITEFURY_SLOT_A_PAYLOAD="${LITEFURY_SLOT_A_PAYLOAD:-0x680100}"
export LITEFURY_SLOT_B_PAYLOAD="${LITEFURY_SLOT_B_PAYLOAD:-0xa80100}"

export GOLDENGATE_CHECK_GOLDEN_CMD="${GOLDENGATE_CHECK_GOLDEN_CMD:-${tools_dir}/litefury-check-golden.sh}"
export GOLDENGATE_WARMBOOT_APP_CMD="${GOLDENGATE_WARMBOOT_APP_CMD:-GOLDENGATE_LITEFURY_WARMBOOT_CONFIRM=JUMP_TO_VERIFIED_SLOT ${tools_dir}/litefury-warmboot-slot.sh A}"
export GOLDENGATE_RESCAN_CMD="${GOLDENGATE_RESCAN_CMD:-GOLDENGATE_LITEFURY_RESCAN_CONFIRM=CONTROLLED_RESCAN ${tools_dir}/litefury-pcie-rescan.sh}"
export GOLDENGATE_CHECK_APP_CMD="${GOLDENGATE_CHECK_APP_CMD:-${tools_dir}/litefury-check-app.sh}"
export GOLDENGATE_RETURN_GOLDEN_CMD="${GOLDENGATE_RETURN_GOLDEN_CMD:-GOLDENGATE_LITEFURY_RETURN_CONFIRM=RETURN_TO_GOLDEN ${tools_dir}/litefury-return-golden.sh}"
export GOLDENGATE_ARM_WATCHDOG_CMD="${GOLDENGATE_ARM_WATCHDOG_CMD:-GOLDENGATE_LITEFURY_WATCHDOG_CONFIRM=ARM_WATCHDOG ${tools_dir}/litefury-watchdog.sh arm}"
export GOLDENGATE_PET_WATCHDOG_CMD="${GOLDENGATE_PET_WATCHDOG_CMD:-${tools_dir}/litefury-watchdog.sh pet}"
export GOLDENGATE_CHECK_WATCHDOG_RETURN_CMD="${GOLDENGATE_CHECK_WATCHDOG_RETURN_CMD:-${tools_dir}/litefury-check-golden.sh}"

export GOLDENGATE_APP_CYCLE_SLOT_A_CMD="${GOLDENGATE_APP_CYCLE_SLOT_A_CMD:-GOLDENGATE_LITEFURY_CYCLE_CONFIRM=RUN_SLOT_CYCLE ${tools_dir}/litefury-cycle-slot.sh A}"
export GOLDENGATE_APP_CYCLE_SLOT_B_CMD="${GOLDENGATE_APP_CYCLE_SLOT_B_CMD:-GOLDENGATE_LITEFURY_CYCLE_CONFIRM=RUN_SLOT_CYCLE ${tools_dir}/litefury-cycle-slot.sh B}"

export GOLDENGATE_PREPARE_SLOT_A_CMD="${GOLDENGATE_PREPARE_SLOT_A_CMD:-${tools_dir}/litefury-slot-plan.sh}"
export GOLDENGATE_PREPARE_SLOT_B_CMD="${GOLDENGATE_PREPARE_SLOT_B_CMD:-${tools_dir}/litefury-slot-plan.sh}"
export GOLDENGATE_ROOT="${GOLDENGATE_ROOT:-${repo_root}}"
